import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/_index.tsx"),
  route("auth", "routes/auth.tsx"),
  route("logout", "routes/logout.tsx"),
  route("onboarding", "routes/onboarding.tsx"),
  route("strains", "routes/strains.tsx"),
  route("strains/:slug", "routes/strains.$slug.tsx"),
  route("strains/:slug/review", "routes/strains.$slug.review.tsx"),
  route("community", "routes/community.tsx"),
  route("editorial", "routes/editorial.tsx"),
  route("ds", "routes/ds.tsx"),
  route("terminos", "routes/terminos.tsx"),
  route("privacidad", "routes/privacidad.tsx"),
  route("profile", "routes/profile.tsx"),
  route("profile/:userId", "routes/profile.$userId.tsx"),
  route("profile/edit", "routes/profile_.edit.tsx"),
  route("profile/saved", "routes/profile_.saved.tsx"),
  route("admin", "routes/admin.tsx", [
    index("routes/admin._index.tsx"),
    route("strains", "routes/admin.strains.tsx"),
    route("reviews", "routes/admin.reviews.tsx"),
  ]),
  route("api/reviews/:reviewId/vote", "routes/api/reviews.$reviewId.vote.tsx"),
  route("api/strains/:strainId/save", "routes/api/strains.$strainId.save.tsx"),
  route("api/theme", "routes/api/theme.tsx"),
  route("api/newsletter", "routes/api/newsletter.tsx"),
  route("sitemap.xml", "routes/sitemap[.]xml.tsx"),
] satisfies RouteConfig;
