import {
  Search,
  Menu,
  X,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  ArrowRight,
  ArrowLeft,
  Bookmark,
  BookmarkCheck,
  Share2,
  Star,
  Check,
  Plus,
  Sparkles,
  Zap,
  Leaf,
  Coffee,
  Flame,
  Droplet,
  Smile,
  AlertTriangle,
  Camera,
  User,
  Users,
  BookOpen,
  Mail,
  Lock,
  Eye,
  EyeOff,
  Map,
  Filter,
  SlidersHorizontal,
  LayoutGrid,
  List,
  ThumbsUp,
  ThumbsDown,
  Sun,
  Moon,
  Sprout,
  History,
  Target,
  Palette,
  Utensils,
  Wind,
  Cookie,
  Gem,
  HelpCircle,
  Send,
  Edit3,
  LogIn,
  LogOut,
  Settings,
  Crown,
  TreePine,
  type LucideIcon,
} from "lucide-react";

const registry = {
  search: Search,
  menu: Menu,
  close: X,
  x: X,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  bookmark: Bookmark,
  bookmarkOn: BookmarkCheck,
  share: Share2,
  star: Star,
  check: Check,
  plus: Plus,
  sparkle: Sparkles,
  bolt: Zap,
  leaf: Leaf,
  cup: Coffee,
  flame: Flame,
  droplet: Droplet,
  smile: Smile,
  alert: AlertTriangle,
  camera: Camera,
  user: User,
  users: Users,
  book: BookOpen,
  mail: Mail,
  lock: Lock,
  eye: Eye,
  eyeOff: EyeOff,
  map: Map,
  filter: Filter,
  sliders: SlidersHorizontal,
  grid: LayoutGrid,
  list: List,
  thumbUp: ThumbsUp,
  thumbDown: ThumbsDown,
  sun: Sun,
  moon: Moon,
  sprout: Sprout,
  history: History,
  target: Target,
  palette: Palette,
  fork: Utensils,
  pipe: Wind,
  vape: Wind,
  cookie: Cookie,
  diamond: Gem,
  question: HelpCircle,
  send: Send,
  edit: Edit3,
  login: LogIn,
  logout: LogOut,
  settings: Settings,
  crown: Crown,
  tree: TreePine,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof registry;

export function Icon({
  name,
  size = 18,
  strokeWidth = 1.6,
  className,
  "aria-hidden": ariaHidden = true,
}: {
  name: IconName;
  size?: number;
  strokeWidth?: number;
  className?: string;
  "aria-hidden"?: boolean;
}) {
  const Cmp = registry[name];
  return (
    <Cmp
      size={size}
      strokeWidth={strokeWidth}
      className={className}
      aria-hidden={ariaHidden}
    />
  );
}
