#!/usr/bin/env npx tsx
/**
 * Bulk upload strain card images to Cloudinary
 * and update strains.json with the resulting URLs.
 *
 * Usage:
 *   npx tsx scripts/upload-strain-cards.ts
 *
 * Requires:
 *   - .env with CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET
 *   - strain cards in ../Weedhub/strain-cards/ (generated by gen_strain_cards.py)
 *   - seed/data/strains.json
 *
 * Options:
 *   --dry-run    Show what would be uploaded without actually uploading
 *   --limit=N    Only upload first N cards (for testing)
 *   --skip-existing  Skip strains that already have an imageUrl
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { v2 as cloudinary } from "cloudinary";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ── Load .env ──
const envPath = path.resolve(__dirname, "..", ".env");
if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, "utf-8");
  for (const line of envContent.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx);
    const value = trimmed.slice(eqIdx + 1);
    if (!process.env[key]) process.env[key] = value;
  }
}

// ── Configure Cloudinary ──
cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
});

// ── Parse args ──
const args = process.argv.slice(2);
const DRY_RUN = args.includes("--dry-run");
const SKIP_EXISTING = args.includes("--skip-existing");
const limitArg = args.find((a) => a.startsWith("--limit="));
const LIMIT = limitArg ? parseInt(limitArg.split("=")[1]) : Infinity;

// ── Paths ──
const PROJECT_DIR = path.resolve(__dirname, "..");
const CARDS_DIR = path.resolve(PROJECT_DIR, "strain-cards");
const STRAINS_JSON = path.resolve(PROJECT_DIR, "seed", "data", "strains.json");

async function uploadCard(filePath: string, slug: string): Promise<string> {
  return new Promise((resolve, reject) => {
    cloudinary.uploader.upload(
      filePath,
      {
        folder: "weedhub/strains",
        public_id: slug,
        overwrite: true,
        resource_type: "image",
        transformation: [
          { width: 1080, height: 1080, crop: "fill", quality: "auto", format: "webp" },
        ],
      },
      (error, result) => {
        if (error || !result) {
          reject(error || new Error("Upload failed"));
        } else {
          resolve(result.secure_url);
        }
      }
    );
  });
}

async function main() {
  console.log("🌿 WeedHub Strain Card Uploader\n");

  // Verify Cloudinary config
  if (!process.env.CLOUDINARY_CLOUD_NAME || !process.env.CLOUDINARY_API_KEY) {
    console.error("❌ Missing Cloudinary config. Check your .env file.");
    process.exit(1);
  }
  console.log(`☁️  Cloudinary: ${process.env.CLOUDINARY_CLOUD_NAME}`);

  // Verify cards directory
  if (!fs.existsSync(CARDS_DIR)) {
    console.error(`❌ Cards directory not found: ${CARDS_DIR}`);
    console.error("   Run gen_strain_cards.py --all first.");
    process.exit(1);
  }

  // Load strains
  const strains: any[] = JSON.parse(fs.readFileSync(STRAINS_JSON, "utf-8"));
  console.log(`📋 ${strains.length} strains loaded`);

  if (DRY_RUN) console.log("🔍 DRY RUN — no uploads will be made\n");

  let uploaded = 0;
  let skipped = 0;
  let errors = 0;

  for (const strain of strains) {
    if (uploaded >= LIMIT) break;

    const slug = strain.slug;
    const cardPath = path.join(CARDS_DIR, `${slug}.png`);

    // Skip if no card file
    if (!fs.existsSync(cardPath)) {
      console.log(`  ⚠ No card for ${slug}, skipping`);
      skipped++;
      continue;
    }

    // Skip existing if flag set
    if (SKIP_EXISTING && strain.imageUrl) {
      skipped++;
      continue;
    }

    if (DRY_RUN) {
      console.log(`  📤 Would upload: ${slug} → weedhub/strains/${slug}`);
      uploaded++;
      continue;
    }

    try {
      const url = await uploadCard(cardPath, slug);
      strain.imageUrl = url;
      uploaded++;

      if (uploaded % 25 === 0 || uploaded <= 5) {
        console.log(`  ✓ ${uploaded}. ${strain.name} → ${url.substring(0, 60)}...`);
      }
      if (uploaded % 100 === 0) {
        console.log(`  ... ${uploaded}/${Math.min(strains.length, LIMIT)}`);
      }

      // Brief pause to avoid rate limits
      if (uploaded % 50 === 0) {
        await new Promise((r) => setTimeout(r, 1000));
      }
    } catch (err: any) {
      console.error(`  ✗ Failed: ${slug} — ${err.message}`);
      errors++;
    }
  }

  // Save updated strains.json
  if (!DRY_RUN && uploaded > 0) {
    fs.writeFileSync(STRAINS_JSON, JSON.stringify(strains, null, 2));
    console.log(`\n💾 Updated strains.json with ${uploaded} image URLs`);
  }

  console.log(`\n✅ Done!`);
  console.log(`   📤 Uploaded: ${uploaded}`);
  console.log(`   ⏭  Skipped: ${skipped}`);
  console.log(`   ❌ Errors: ${errors}`);

  if (!DRY_RUN && uploaded > 0) {
    console.log(`\n🔄 Next step: re-seed your database:`);
    console.log(`   npx tsx seed/seed-full.ts`);
  }
}

main().catch((err) => {
  console.error("❌ Fatal:", err);
  process.exit(1);
});
